places = ["japan", "germany", "new york", "switzerland", "boston"]
print(sorted(places, reverse= True))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.reverse()
print(places)